print('Hello Friend')
print('See git is easy!')
print('Adding new lines in Branch 1')
print("These lines won't be visible from master branch, unless you merged with master branch")
print("Exploring Git Gui")